### ISSUE TITLE
Alteração do titulo da seção Biblioteca de Plugins para Jquery

### ISSUE THREAD

**Issue by paoloalmeida** [LFeh/useful-tools#12]
Fala Felipe, tranquilo?
Cara, o titulo da seção "Biblioteca de Plugins para Jquery", me pareceu limitar somente ao Jquery e não ao Javascript como um todo, não sei se é exatamente essa a idéia, já que há muitas libs de JS que não necessitam propriamente de Jquery. Sugiro, alterar para Biblioteca de Plugins para Javascipt, o que acha?

Abs.

**Comment by LFeh** [comment]
Acho muito bom ;)

Quer fazer essa alteração? Abraços!

**Comment by paoloalmeida** [comment]
Feita :)
