### ISSUE TITLE
CLI Tools?

### ISSUE THREAD

**Issue by afonsopacifer** [LFeh/useful-tools#6]
Que tal adicionar ferramentas de linha de comando a lista?

**Comment by LFeh** [comment]
Tem ferramentas desse tipo online?

**Comment by afonsopacifer** [comment]
Não, 
a ideia era expandir a lista para englobar ferramentas offline como grunt, bower, etc...
mas pode fugir do objetivo, ai você que sabe.

Mudando de assunto,
eu tava pensando em sugerir:
caniuse.com
responsinator.com
stackoverflow.com
mas não achei bem em que categoria colocar, tem alguma ideia?
Não sei se é ruim subdividir muito as categorias, sei la.

**Comment by LFeh** [comment]
Então @afonsopacifer, a ideia era ser um repo só para ferramentas online mesmo. Então não vejo muita necessidade de adicionar esses sites.

**Comment by afonsopacifer** [comment]
sim sim, blz.
